### ISSUE TITLE
win10-64bit?

### ISSUE THREAD

**Issue by arriver** [kaseat/MinerWatchdog#1]
Пишет, что не может запуститься в 64 битах

**Comment by kaseat** [comment]
На какой операционной системе запускаете?

**Comment by arriver** [comment]
ну win10-64bit.. могу завтра скрин кинуть

**Comment by kaseat** [comment]
баранки гну... Проверил на четырёх машинах с win10, проблем нет нигде. Народ тоже не жалуется. Судя по всему проблема в вашей windows. Исходники открыты, компилируйте под свою систему.
