### ISSUE TITLE
Не правильно работает ребутер

### ISSUE THREAD

**Issue by CmRaD4u** [kaseat/MinerWatchdog#2]
Проблема такая: 
Майнер EWBF 
Если отрубается инет - скорость видюхи соотв. падает и прога ребутает майнер. Но после первого ребута, если интернета все еще нет, вотчдог виснет на ребуте.
Я предлагаю сделать так, если инет есть, а скорость видюхи упала - то ребут
Если инета нет, а скорость видюхи упала - не ребутить
Почему так - Майнер сам переконекчивает инет.
Прошу отписаться в cmrad4u@gmail.com и вот адрес странички вк vk.com/cmrad4u

**Comment by kaseat** [comment]
Начиная с билда [1.0.0.1](https://github.com/kaseat/MinerWatchdog/blob/master/Builds/1.0.0.1/WDG.exe?raw=true) добавлена возможность отключить проверку интернет соединения командой "-checkInet false".

**Comment by CmRaD4u** [comment]
Спасибо, но напиши в любом случае по какому-то из адресов, хочу расспросить))
